package rbac

import (
	"fmt"
	"sort"
	"strings"

	"github.com/pangu-studio/mozi-builder/mozi"
)

type Request struct{ Principal, Resource, Action, OwnerID, ActorID, TenantID, ActorTenantID string }

// Allowed is deny-first. Conditions outside the supported ownership/tenant
// subset deliberately fail closed and belong in application policy code.
func Allowed(rules []mozi.PermissionIR, req Request) bool {
	allowed := false
	for _, rule := range rules {
		if !matches(rule.Principal, req.Principal) || !matches(rule.Resource, req.Resource) || !matches(rule.Action, req.Action) {
			continue
		}
		if !scopeMatches(rule.Scope, req) || rule.Condition != "" {
			continue
		}
		if rule.Effect == "deny" {
			return false
		}
		allowed = true
	}
	return allowed
}

func matches(pattern, value string) bool { return pattern == "*" || pattern == value }
func scopeMatches(scope string, req Request) bool {
	switch scope {
	case "", "all":
		return true
	case "own":
		return req.ActorID != "" && req.ActorID == req.OwnerID
	case "tenant":
		return req.ActorTenantID != "" && req.ActorTenantID == req.TenantID
	default:
		return false
	}
}

func GenerateGo(model *mozi.ModelIR) string {
	var actions []string
	seen := map[string]bool{}
	for _, rule := range model.Semantics.PermissionRules {
		if !seen[rule.Action] {
			seen[rule.Action] = true
			actions = append(actions, rule.Action)
		}
	}
	sort.Strings(actions)
	var b strings.Builder
	b.WriteString("// Code generated by mozi. Implement policy wiring in application code.\npackage permissions\n\nimport \"context\"\n\ntype Check struct { Principal, Resource, Action, OwnerID, TenantID string }\ntype Authorizer interface { Authorize(context.Context, Check) error }\n\n")
	for _, action := range actions {
		fmt.Fprintf(&b, "const Action%s = %q\n", pascal(action), action)
	}
	return b.String()
}

func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' })
	for i := range parts {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
