package sdk

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

type document struct {
	Paths       map[string]map[string]operation `json:"paths"`
	Definitions map[string]schema               `json:"definitions"`
	Components  struct {
		Schemas map[string]schema `json:"schemas"`
	} `json:"components"`
}
type operation struct {
	OperationID string              `json:"operationId"`
	Parameters  []parameter         `json:"parameters"`
	Responses   map[string]response `json:"responses"`
}
type parameter struct {
	Name     string `json:"name"`
	In       string `json:"in"`
	Required bool   `json:"required"`
	Schema   schema `json:"schema"`
	Type     string `json:"type"`
}
type response struct {
	Schema  schema `json:"schema"`
	Content map[string]struct {
		Schema schema `json:"schema"`
	} `json:"content"`
}
type schema struct {
	Ref        string            `json:"$ref"`
	Type       string            `json:"type"`
	Required   []string          `json:"required"`
	Properties map[string]schema `json:"properties"`
	Items      *schema           `json:"items"`
}

func GenerateTypeScript(data []byte) (string, error) {
	var d document
	if err := json.Unmarshal(data, &d); err != nil {
		return "", err
	}
	schemas := d.Definitions
	if len(schemas) == 0 {
		schemas = d.Components.Schemas
	}
	var b strings.Builder
	b.WriteString("// Code generated by mozi from OpenAPI. DO NOT EDIT.\n\nexport interface RequestOptions { signal?: AbortSignal; headers?: Record<string, string> }\nexport type APIError = { error: { code: string; message: string; details?: unknown; request_id?: string } }\n\n")
	names := make([]string, 0, len(schemas))
	for n := range schemas {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(&b, "export interface %s %s\n\n", safeType(n), objectType(schemas[n]))
	}
	type endpoint struct {
		path, method string
		op           operation
	}
	var eps []endpoint
	for p, methods := range d.Paths {
		for m, op := range methods {
			if op.OperationID != "" {
				eps = append(eps, endpoint{p, m, op})
			}
		}
	}
	sort.Slice(eps, func(i, j int) bool { return eps[i].op.OperationID < eps[j].op.OperationID })
	b.WriteString("export class APIClient {\n  constructor(private readonly baseUrl: string, private readonly fetcher: typeof fetch = fetch) {}\n")
	for _, e := range eps {
		ret := responseType(e.op)
		fmt.Fprintf(&b, "  async %s(params: Record<string, unknown> = {}, options: RequestOptions = {}): Promise<%s> {\n", safeIdent(e.op.OperationID), ret)
		path := e.path
		for _, p := range e.op.Parameters {
			if p.In == "path" {
				path = strings.ReplaceAll(path, "{"+p.Name+"}", "${encodeURIComponent(String(params."+p.Name+"))}")
			}
		}
		fmt.Fprintf(&b, "    const response = await this.fetcher(`${this.baseUrl}%s`, { method: %q, signal: options.signal, headers: { 'Content-Type': 'application/json', ...options.headers }, body: %s });\n", path, strings.ToUpper(e.method), bodyExpr(e.method))
		b.WriteString("    if (!response.ok) throw await response.json() as APIError;\n    return await response.json() as " + ret + ";\n  }\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func objectType(s schema) string {
	if s.Type != "object" && len(s.Properties) == 0 {
		return "{ [key: string]: unknown }"
	}
	req := map[string]bool{}
	for _, r := range s.Required {
		req[r] = true
	}
	keys := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("{\n")
	for _, k := range keys {
		optional := "?"
		if req[k] {
			optional = ""
		}
		fmt.Fprintf(&b, "  %s%s: %s\n", safeIdent(k), optional, tsType(s.Properties[k]))
	}
	b.WriteString("}")
	return b.String()
}
func tsType(s schema) string {
	if s.Ref != "" {
		parts := strings.Split(s.Ref, "/")
		return safeType(parts[len(parts)-1])
	}
	switch s.Type {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		if s.Items != nil {
			return tsType(*s.Items) + "[]"
		}
		return "unknown[]"
	case "object":
		return objectType(s)
	default:
		return "unknown"
	}
}
func responseType(op operation) string {
	for _, code := range []string{"200", "201", "202"} {
		if r, ok := op.Responses[code]; ok {
			if r.Schema.Ref != "" || r.Schema.Type != "" {
				return tsType(r.Schema)
			}
			for _, m := range r.Content {
				return tsType(m.Schema)
			}
		}
	}
	return "unknown"
}
func bodyExpr(method string) string {
	switch strings.ToUpper(method) {
	case "POST", "PUT", "PATCH":
		return "JSON.stringify(params.body ?? params)"
	default:
		return "undefined"
	}
}
func safeType(s string) string {
	return strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			return r
		}
		return '_'
	}, s)
}
func safeIdent(s string) string { return safeType(s) }
