package generator

import (
	"fmt"
	"regexp"
	"strings"
)

// MarkerSection represents a mozi-managed code section bounded by marker comments.
type MarkerSection struct {
	Name      string // section name (e.g., "ListUser")
	Start     string // full start marker line
	End       string // full end marker line
	Content   string // content between markers (without the marker lines)
	LineStart int    // line number where start marker appears
	LineEnd   int    // line number where end marker appears
}

// markerPattern matches mozi marker comments.
// Go:    // mozi:section Name — description
//
//	// mozi:end Name
//
// TSX:   // mozi:columns Name — description
//
//	// mozi:end columns Name
//	// mozi:api Name
//	// mozi:end Name
//
// Route: // mozi:section InitName — ...
//
//	// mozi:end InitName
var (
	markerStartRe = regexp.MustCompile(`(?m)^(\s*(?://|{/\*)\s*mozi:(section|columns|api|route|import|menu)\s+(\S+).*)$`)
	markerEndRe   = regexp.MustCompile(`(?m)^(\s*(?://|{/\*)\s*mozi:end\s+(\S+).*)$`)
)

// ExtractMarkerSections extracts all mozi-managed sections from source code.
func ExtractMarkerSections(source string) []MarkerSection {
	var sections []MarkerSection
	lines := strings.Split(source, "\n")

	// Find all start/end marker pairs
	type pending struct {
		name      string
		startLine int
	}
	openSections := make(map[string]pending) // marker name → pending
	var orderedNames []string

	for i, line := range lines {
		if matches := markerEndRe.FindStringSubmatch(line); matches != nil {
			name := matches[2]
			if p, ok := openSections[name]; ok {
				content := strings.Join(lines[p.startLine+1:i], "\n")
				sections = append(sections, MarkerSection{
					Name:      name,
					Start:     lines[p.startLine],
					End:       line,
					Content:   content,
					LineStart: p.startLine,
					LineEnd:   i,
				})
				delete(openSections, name)
				orderedNames = removeString(orderedNames, name)
			}
		} else if matches := markerStartRe.FindStringSubmatch(line); matches != nil {
			name := matches[3]
			openSections[name] = pending{name: name, startLine: i}
			orderedNames = append(orderedNames, name)
		}
	}

	return sections
}

// ReplaceMarkerSection replaces the content of a named marker section in the source.
// If the section exists, its content is replaced. If not, the new section is appended.
func ReplaceMarkerSection(source, sectionName, sectionType, newContent string) string {
	sections := ExtractMarkerSections(source)

	// Find existing section
	for _, s := range sections {
		if s.Name == sectionName {
			lines := strings.Split(source, "\n")
			indent := extractIndent(s.Start)
			newLines := indentLines(newContent, indent)
			newSection := s.Start + "\n" + newLines + "\n" + s.End

			result := strings.Join(lines[:s.LineStart], "\n")
			if s.LineStart > 0 {
				result += "\n"
			}
			result += newSection
			if s.LineEnd < len(lines)-1 {
				result += "\n" + strings.Join(lines[s.LineEnd+1:], "\n")
			}
			return result
		}
	}

	// Section doesn't exist — append
	startMarker := fmt.Sprintf("// mozi:%s %s — auto-generated by mozi", sectionType, sectionName)
	endMarker := fmt.Sprintf("// mozi:end %s", sectionName)
	newSection := "\n" + startMarker + "\n" + newContent + "\n" + endMarker + "\n"
	return strings.TrimRight(source, "\n") + newSection
}

func extractIndent(line string) string {
	for i, c := range line {
		if c != ' ' && c != '\t' {
			return line[:i]
		}
	}
	return ""
}

func indentLines(content, indent string) string {
	if content == "" {
		return indent
	}
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = indent + line
		}
	}
	return strings.Join(lines, "\n")
}

func removeString(slice []string, s string) []string {
	for i, v := range slice {
		if v == s {
			return append(slice[:i], slice[i+1:]...)
		}
	}
	return slice
}
